# Generated by Django 5.1.2 on 2024-10-31 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id_permi', models.BigAutoField(help_text='Identificador único para el permiso.', primary_key=True, serialize=False, verbose_name='ID del Permiso')),
                ('name', models.CharField(help_text='Nombre descriptivo del permiso.', verbose_name='Nombre del Permiso')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del permiso y su propósito.', verbose_name='Descripción')),
                ('can_create', models.BooleanField(default=False, help_text='Permite crear nuevos registros.', verbose_name='Puede Crear')),
                ('can_read', models.BooleanField(default=False, help_text='Permite ver registros existentes.', verbose_name='Puede Leer')),
                ('can_update', models.BooleanField(default=False, help_text='Permite modificar registros existentes.', verbose_name='Puede Actualizar')),
                ('can_delete', models.BooleanField(default=False, help_text='Permite eliminar registros existentes.', verbose_name='Puede Eliminar')),
                ('can_import', models.BooleanField(default=False, help_text='Permite importar datos masivamente.', verbose_name='Puede Importar')),
                ('can_export', models.BooleanField(default=False, help_text='Permite exportar datos del sistema.', verbose_name='Puede Exportar')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(help_text='Identificador único para el usuario.', primary_key=True, serialize=False, verbose_name='ID de Usuario')),
                ('user_username', models.CharField(help_text='Nombre de usuario para iniciar sesión.', unique=True, verbose_name='Nombre de Usuario')),
                ('user_password', models.CharField(help_text='Contraseña encriptada del usuario.', verbose_name='Contraseña')),
                ('user_email', models.EmailField(help_text='Dirección de correo electrónico del usuario.', max_length=254, unique=True, verbose_name='Correo Electrónico')),
                ('user_phone', models.CharField(blank=True, help_text='Número de teléfono del usuario.', verbose_name='Teléfono')),
                ('user_is_admin', models.BooleanField(default=False, help_text='Indica si el usuario es Administrador (True) o normal (False).', verbose_name='Usuario Administrador')),
                ('user_is_active', models.BooleanField(default=True, help_text='Indica si el usuario está activo (True) o inactivo (False).', verbose_name='Usuario Activo')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_role', models.BigAutoField(help_text='Identificador único para el rol.', primary_key=True, serialize=False, verbose_name='ID del Rol')),
                ('role_code', models.CharField(help_text='Código único para identificar el rol dentro de la compañía.', max_length=50, verbose_name='Código del Rol')),
                ('role_name', models.CharField(help_text='Nombre descriptivo del rol.', verbose_name='Nombre del Rol')),
                ('role_description', models.TextField(blank=True, help_text='Descripción detallada del rol y sus responsabilidades.', verbose_name='Descripción')),
                ('role_active', models.BooleanField(default=True, help_text='Indica si el rol está activo (True) o inactivo (False).', verbose_name='Estado del Rol')),
                ('company', models.ForeignKey(help_text='Compañía a la que pertenece este rol.', on_delete=django.db.models.deletion.PROTECT, related_name='company_roles', to='core.company', verbose_name='Compañía')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'unique_together': {('company', 'role_code')},
            },
        ),
        migrations.CreateModel(
            name='PermiRoleRecord',
            fields=[
                ('id_perrc', models.BigAutoField(help_text='Identificador único para el permiso de rol por registro.', primary_key=True, serialize=False, verbose_name='ID de Permiso de Rol por Registro')),
                ('perrc_record', models.BigIntegerField(help_text='Identificador del registro específico al que se aplica el permiso.', verbose_name='ID de Registro')),
                ('perrc_include', models.BooleanField(default=True, help_text='Indica si el permiso se incluye (True) o se excluye (False) para el rol y registro.', verbose_name='Incluir Permiso')),
                ('entitycatalog', models.ForeignKey(help_text='Entidad sobre la que se aplica el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='entity_role_record_permissions', to='core.entitycatalog', verbose_name='Entidad')),
                ('permission', models.ForeignKey(help_text='Permiso asignado al rol.', on_delete=django.db.models.deletion.PROTECT, related_name='permission_role_records', to='user.permission', verbose_name='Permiso')),
                ('role', models.ForeignKey(help_text='Rol al que se asigna el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='role_record_permissions', to='user.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol por Registro',
                'verbose_name_plural': 'Permisos de Rol por Registro',
                'unique_together': {('role', 'permission', 'entitycatalog', 'perrc_record')},
            },
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id_useco', models.BigAutoField(help_text='Identificador único para la relación usuario-compañía.', primary_key=True, serialize=False, verbose_name='ID de Usuario por Compañía')),
                ('useco_active', models.BooleanField(default=True, help_text='Indica si la relación usuario-compañía está activa (True) o inactiva (False).', verbose_name='Estado de la Relación')),
                ('company', models.ForeignKey(help_text='Compañía asociada al usuario.', on_delete=django.db.models.deletion.PROTECT, related_name='company_users', to='core.company', verbose_name='Compañía')),
                ('user', models.ForeignKey(help_text='Usuario asociado a la compañía.', on_delete=django.db.models.deletion.PROTECT, related_name='user_companies', to='user.user', verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Usuario por Compañía',
                'verbose_name_plural': 'Usuarios por Compañía',
                'unique_together': {('user', 'company')},
            },
        ),
        migrations.CreateModel(
            name='PermiRole',
            fields=[
                ('id_perol', models.BigAutoField(help_text='Identificador único para el permiso de rol.', primary_key=True, serialize=False, verbose_name='ID de Permiso de Rol')),
                ('perol_include', models.BooleanField(default=True, help_text='Indica si el permiso se incluye (True) o se excluye (False) para el rol.', verbose_name='Incluir Permiso')),
                ('entitycatalog', models.ForeignKey(help_text='Entidad sobre la que se aplica el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='entity_role_permissions', to='core.entitycatalog', verbose_name='Entidad')),
                ('perol_record', models.ForeignKey(help_text='Registro de permiso de rol.', on_delete=django.db.models.deletion.PROTECT, related_name='perol_permissions', to='user.permirolerecord', verbose_name='Registro de Permiso de Rol')),
                ('permission', models.ForeignKey(help_text='Permiso asignado al rol.', on_delete=django.db.models.deletion.PROTECT, related_name='permission_roles', to='user.permission', verbose_name='Permiso')),
                ('role', models.ForeignKey(help_text='Rol al que se asigna el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='role_permissions', to='user.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Rol',
                'unique_together': {('role', 'permission', 'entitycatalog', 'perol_record')},
            },
        ),
        migrations.CreateModel(
            name='PermiUserRecord',
            fields=[
                ('id_peusr', models.BigAutoField(help_text='Identificador único para el permiso de usuario.', primary_key=True, serialize=False, verbose_name='ID de Permiso de Usuario')),
                ('peusr_record', models.BigIntegerField(help_text='Identificador del registro específico de la entidad al que aplica el permiso.', verbose_name='ID del Registro')),
                ('peusr_include', models.BooleanField(default=True, help_text='Indica si el permiso se incluye (True) o se excluye (False) para el usuario.', verbose_name='Incluir Permiso')),
                ('entitycatalog', models.ForeignKey(help_text='Entidad sobre la que se aplica el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='entity_permissions', to='core.entitycatalog', verbose_name='Entidad')),
                ('permission', models.ForeignKey(help_text='Permiso asignado al usuario.', on_delete=django.db.models.deletion.PROTECT, related_name='permission_users', to='user.permission', verbose_name='Permiso')),
                ('usercompany', models.ForeignKey(help_text='Relación usuario-compañía a la que se asigna el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='user_permissions', to='user.usercompany', verbose_name='Usuario por Compañía')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario por Registro',
                'verbose_name_plural': 'Permisos de Usuario por Registro',
                'unique_together': {('usercompany', 'permission', 'entitycatalog', 'peusr_record')},
            },
        ),
        migrations.CreateModel(
            name='PermiUser',
            fields=[
                ('id_peusr', models.BigAutoField(help_text='Identificador único para el permiso de usuario.', primary_key=True, serialize=False, verbose_name='ID de Permiso de Usuario')),
                ('peusr_include', models.BooleanField(default=True, help_text='Indica si el permiso se incluye (True) o se excluye (False) para el usuario.', verbose_name='Incluir Permiso')),
                ('entitycatalog', models.ForeignKey(help_text='Entidad sobre la que se aplica el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='permi_user_entity_permissions', to='core.entitycatalog', verbose_name='Entidad')),
                ('permission', models.ForeignKey(help_text='Permiso asignado al usuario.', on_delete=django.db.models.deletion.PROTECT, related_name='user_permissions', to='user.permission', verbose_name='Permiso')),
                ('usercompany', models.ForeignKey(help_text='Relación usuario-compañía a la que se asigna el permiso.', on_delete=django.db.models.deletion.PROTECT, related_name='permi_user_permissions', to='user.usercompany', verbose_name='Usuario por Compañía')),
            ],
            options={
                'verbose_name': 'Permiso de Usuario',
                'verbose_name_plural': 'Permisos de Usuario',
                'unique_together': {('usercompany', 'permission', 'entitycatalog')},
            },
        ),
    ]
