# Generated by Django 5.1.2 on 2024-11-01 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(help_text='Permisos asociados a este rol.', related_name='role_permissions', to='user.permission', verbose_name='Permisos'),
        ),
    ]
