# Generated by Django 5.1.2 on 2024-11-01 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_role_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='permissions',
        ),
    ]
